### ISSUE TITLE
Basic end to end example in documentation

### ISSUE THREAD

**Issue by ftrotter** [pauly4it/laraturk#3]
Thanks for the clean codebase and project. I am still working through getting this started.

It would be super helpful if you could walk through the basic workflow of creating a HIT with some reasonable items, and the minimal follow through to get data back out of mturk. 

I am learning mturk through your code, so that kind of overview would be very helpful and I think would substantially increase adoption.

At least I am using your codebase over several other comparable ones, precisely because you bothered to invest in a solid starting README. 

Thanks for that.
-FT

**Comment by pauly4it** [comment]
That's a great idea. This weekend I'll take a look at the codebase where I implemented the mturk API and use that to build an example.

**Comment by ftrotter** [comment]
Thank you! closing issue...
