### ISSUE TITLE
Not an issue, just a thanks

### ISSUE THREAD

**Issue by jv2222** [pauly4it/laraturk#5]
Thanks for writing this. I'll be playing with it over the coming weeks and it's great to have this as a starting point.

**Comment by pauly4it** [comment]
Appreciate the thanks! I'm hoping to spend some more time cleaning up the package and making it compatible with newer versions of Laravel. Let me know if you have any suggestions or feedback!

**Comment by jv2222** [comment]
Hey @pauly4it could you do me a quick favor and change the guzzle to this...

"guzzlehttp/guzzle": ">=5"

I can't install it in my current version because of that constraint and I have guzzle version 6.

Thanks!
